###__TEXT_REPLACE_TAG1__###
###__TEXT_REPLACE_TAG2__###

ifndef INSTALLATION_PATH
INSTALLATION_PATH := /usr/local
INSTALLATION_PATH_ESCAPE := \/usr\/local
endif

.PHONY: all test clean install uninstall

all :
	$(MAKE) -C src

test :
	$(MAKE) -C test

clean :
	$(MAKE) -C src clean
	$(MAKE) -C test clean

install : all
	mkdir -p $(INSTALLATION_PATH)/lib
	mkdir -p $(INSTALLATION_PATH)/bin
	cp src/libHb.a $(INSTALLATION_PATH)/lib
	cp src/engine/hb-preprocessor.bin $(INSTALLATION_PATH)/bin/hb-preprocessor
	cp script/hb-build.sh $(INSTALLATION_PATH)/bin/hb-build
	sed -i 's/###__TEXT_REPLACE_TAG__###/linked_lib_path=-L$(INSTALLATION_PATH_ESCAPE)/g' $(INSTALLATION_PATH)/bin/hb-build

uninstall :
	rm -f $(INSTALLATION_PATH)/lib/libHb.a
	rm -f $(INSTALLATION_PATH)/bin/hb-preprocessor