#include "tempo_enum_converter.hpp"

std::map<std::string, hautbois::core::TempoEnum> hautbois::core::tempo_str_enum_convert::TEMPO_STRING_TO_ENUM {
  { "larghissimo", TempoEnum::larghissimo },
  { "adagissimo", TempoEnum::adagissimo },
  { "grave", TempoEnum::grave },
  { "largo", TempoEnum::largo },
  { "lento", TempoEnum::lento },
  { "larghetto", TempoEnum::larghetto },
  { "adagio", TempoEnum::adagio },
  { "adagietto", TempoEnum::adagietto },
  { "andante", TempoEnum::andante },
  { "andantino", TempoEnum::andantino },
  { "marcia_moderato", TempoEnum::marcia_moderato },
  { "andante_moderato", TempoEnum::andante_moderato },
  { "moderato", TempoEnum::moderato },
  { "allegretto", TempoEnum::allegretto },
  { "allegro_moderato", TempoEnum::allegro_moderato },
  { "allegro", TempoEnum::allegro },
  { "molto_allegro", TempoEnum::molto_allegro },
  { "vivace", TempoEnum::vivace },
  { "vivacissimo", TempoEnum::vivacissimo },
  { "vivacissimamente", TempoEnum::vivacissimamente },
  { "allegrissimo", TempoEnum::allegrissimo },
  { "allegro_vivace", TempoEnum::allegro_vivace },
  { "presto", TempoEnum::presto },
  { "prestissimo", TempoEnum::prestissimo }
};

std::map<hautbois::core::TempoEnum, std::string> hautbois::core::tempo_str_enum_convert::TEMPO_ENUM_TO_STRING {
  { TempoEnum::larghissimo, "larghissimo" },
  { TempoEnum::adagissimo, "adagissimo" },
  { TempoEnum::grave, "grave" },
  { TempoEnum::largo, "largo" },
  { TempoEnum::lento, "lento" },
  { TempoEnum::larghetto, "larghetto" },
  { TempoEnum::adagio, "adagio" },
  { TempoEnum::adagietto, "adagietto" },
  { TempoEnum::andante, "andante" },
  { TempoEnum::andantino, "andantino" },
  { TempoEnum::marcia_moderato, "marcia_moderato" },
  { TempoEnum::andante_moderato, "andante_moderato" },
  { TempoEnum::moderato, "moderato" },
  { TempoEnum::allegretto, "allegretto" },
  { TempoEnum::allegro_moderato, "allegro_moderato" },
  { TempoEnum::allegro, "allegro" },
  { TempoEnum::molto_allegro, "molto_allegro" },
  { TempoEnum::vivace, "vivace" },
  { TempoEnum::vivacissimo, "vivacissimo" },
  { TempoEnum::vivacissimamente, "vivacissimamente" },
  { TempoEnum::allegrissimo, "allegrissimo" },
  { TempoEnum::allegro_vivace, "allegro_vivace" },
  { TempoEnum::presto, "presto" },
  { TempoEnum::prestissimo, "prestissimo" }
};